### ISSUE TITLE
Error when building via browserify

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-login-ux#146]
I intermittently see this error when using login with browserify, which causes the browserify process to fail. It happens locally and on travis:

```
Error: Parsing file /Users/k88hudson/github/webmaker-app/node_modules/webmaker-login-ux/src/adapters/plain.js: Unterminated string constant (40:31)
    at Deps.parseDeps (/Users/k88hudson/github/webmaker-app/node_modules/browserify/node_modules/module-deps/index.js:366:28)
    at fromSource (/Users/k88hudson/github/webmaker-app/node_modules/browserify/node_modules/module-deps/index.js:309:48)
    at /Users/k88hudson/github/webmaker-app/node_modules/browserify/node_modules/module-deps/index.js:304:17
    at ConcatStream.<anonymous> (/Users/k88hudson/github/webmaker-app/node_modules/browserify/node_modules/concat-stream/index.js:32:43)
```

**Comment by k88hudson** [comment]
@cadecairos @alicoding have you noticed this?

**Comment by alicoding** [comment]
Not yet, but will give it and try to see if I hit that.

**Comment by cadecairos** [comment]
@errietta hit this last night I think. Haven't seen it myself though.

**Comment by errietta** [comment]
Yes this looks like what I hit

**Comment by k88hudson** [comment]
I see it probably on 5% of builds

**Comment by RangerMauve** [comment]
Did you guys find a solution to this? I've been getting it non-stop in my own project.

**Comment by benmj** [comment]
I'm also having this issue, and have not come to any solution. Does anyone know a reliable way of getting rid of it?

**Comment by RangerMauve** [comment]
@benmj For some reason cloning a project from scratch seemed to help for a few hours, but I have absolutely no idea why.

**Comment by benmj** [comment]
That's really bizarre. @RangerMauve what is your build environment? I'm using Windows 8.1 for this project.

**Comment by RangerMauve** [comment]
Also using 8.1, actually. On my dev machine with an SSD it happens less frequently than my colleague with a hard drive. This leads me to think that read speed might be affecting this somehow. Changing between node 10.x and 12.x didn't affect anything so I doubt it's anything related to that.
